### ISSUE TITLE
sort functions for Data.Set

### ISSUE THREAD

**Issue by flip111** [purescript/purescript-ordered-collections#26]
Since it's ordered collections can some sort functions be added to change the order?

I mean functions like https://pursuit.purescript.org/packages/purescript-arrays/5.3.1/docs/Data.Array#v:sort

**Comment by hdgarrood** [comment]
No, that wouldn’t really make sense for these types. Internally we always order the elements according to the Ord instance, because we rely on this for good performance for operations like lookup/member.

**Comment by flip111** [comment]
After looking around in the haskell eco system i understood the following

"ordered collections" is not about how to work with the data structures (ordered API), but rather an implementation detail. Is that right ?

**Comment by hdgarrood** [comment]
More or less, yeah. It’s not just an implementation detail, because the asymptotics are a little different - O(log n) vs O(1) lookup, for instance. Also if you want to iterate over the elements in key order, Map can do that much more efficiently than HashMap can. The interfaces are indeed pretty similar though.
