### ISSUE TITLE
add toUnfoldableWith?

### ISSUE THREAD

**Issue by safareli** [purescript/purescript-ordered-collections#9]
we have fromFoldableWith but not:
`toUnfoldableWith :: forall f k v a. Unfoldable f => Map k v -> (Tuple k v -> a) -> f a`
I think it would be nice addition as it could be used to extract values or keys in one pass vs 2 (`keys >>> toUnfoldable` or `values >>> toUnfoldable`).

let me know what you think and if you people like this will open a pr

**Comment by garyb** [comment]
`fromFoldableWith` is a bit different, it's there to determine how to resolve value conflicts, rather than giving a `a -> Tuple k v`. That thing would also be useful, but we'd need to come up with a different name for it.

What you're describing can be done using the `FoldableWithIndex` functions already, but I think the unfoldable version might well still be useful.

This is highly relevant to me and @kRITZCREEK as we've just been through all this stuff with some code we were writing yesterday :smile:.

**Comment by safareli** [comment]
ah yes fromFoldableWith is different. Yes FoldableWithIndex can do it, but you would need to append multiple arrays together while toUnfoldable instance of array is more efficient.

if `toUnfoldableWith` is not fine for this maybe `toUnfoldableOver`, `toUnfoldableOn`? :d

**Comment by garyb** [comment]
> but you would need to append multiple arrays together while toUnfoldable instance of array is more efficient

Yeah, I ended up defining `refoldWithIndex f = foldrWithIndex (\ix -> List.Cons <<< go ix) List.Nil` - which is essentially what the `Unfoldable` stuff abstracts - cons-like constructions.

**Comment by safareli** [comment]
yes but if you want to get array and you have `Map` you have to go to List (using values) and then to Array or use foldrWithIndex with List and then to array.

Now you can do something like this:
``` purs
traversableWithIndexToArray :: forall a b. TraversableWithIndex i f => (i -> a -> b) -> f a -> Array b
traversableWithIndexToArray f i = runPure $ runST do
  arr <- emptySTArray
  forWithIndex_ i $ f >>> pushSTArray arr
  unsafeFreeze arr
```
but it's not that great and might be less efficient actually

**Comment by JordanMartinez** [comment]
It sounds like this issue should be closed. Please reopen if you disagree.
